"""
Agent 6: Report Agent
Generates a comprehensive final business report summarizing the entire pipeline.
"""
import json
import time
from . import BaseAgent


class ReportAgent(BaseAgent):
    """Generates a final executive report from the full pipeline context."""

    def __init__(self, client):
        super().__init__(client)
        self.name = "ReportAgent"

    def run(self, pipeline_context):
        """
        Synthesize the final reports (Business and Judge Trace) using the full pipeline context.
        Returns: (report_data, trace)
        """
        start = time.time()
        
        prompt = f"""You are Agent 06 — Outcome Visualization Agent — the final agent in an Antigravity-orchestrated system.

You receive the COMPLETE pipeline_context including all agent outputs AND all agent_traces.

Your job: produce the final human-readable report AND a structured judge-facing trace document.

## You must produce TWO outputs:

### OUTPUT A: Business Report (Markdown)
Sections (all required, in this order):
1. Executive Summary (3-4 sentences)
2. Insight Found (Title, details with numbers, confidence, urgency)
3. Impact Assessment (Severity score/5, stakeholders, financial risk, cost of inaction)
4. Action Taken (Table with Action, Owner, Timeline, Tools)
5. Before vs After (Table with at least 3 rows of real numbers from simulation)
6. Execution Log (Full log from simulation with timestamps and statuses)
7. Projected Outcome (Metric, baseline, projected, timeframe, confidence)
8. Next Recommended Steps (2-3 manual actions with owners)

---
*Generated by Autonomous Agentic AI System | Run ID: [run_id] | [timestamp]*

### OUTPUT B: Agent Trace Document (Markdown — for judges)
Title: ## Agent Reasoning Trace — Run [run_id]

For each agent (01 through 05):
#### Agent [N]: [Name]
- Reasoning steps (numbered list)
- Options considered
- Decision made
- Flags raised
- Duration hint

Then:
#### Orchestrator Log
- All orchestrator decisions and pipeline management steps

#### Pipeline Summary
| Agent | Status | Key Decision | Confidence |
|-------|--------|-------------|------------|

## Rules:
- All numbers must come from pipeline_context — never invent
- Both outputs are Markdown — clean, formatted, no code blocks around the markdown itself
- Before/After table must have at least 3 rows
- Agent Trace document must cover all 5 agents + orchestrator
- End business report with Run ID footer

Return ONLY a valid JSON object (no markdown wrapping the JSON):
{{
  "business_report": "string (markdown)",
  "trace_document": "string (markdown)",
  "run_id": "{pipeline_context.get('run_id')}",
  "timestamp": "{pipeline_context.get('started_at')}",
  "agent_trace": {{
    "agent": "OutcomeVisualization",
    "reasoning_steps": [
      "Synthesized data from all 5 operational agents",
      "Drafted human-readable business impact report",
      "Generated judge-facing transparency trace from context",
      "Validated all numbers against simulation outputs"
    ],
    "options_considered": ["Visual vs Textual layout", "Technical vs Executive tone"],
    "decision_made": "Final 6-agent synthesis complete"
  }}
}}

FULL PIPELINE CONTEXT:
{json.dumps(pipeline_context, indent=2)}
"""
        try:
            response_text = self._call_gemini(prompt)
            report = self._parse_json_response(response_text)
            duration = int((time.time() - start) * 1000)

            # Standardized Agent Trace
            agent_trace_data = report.get("agent_trace", {})
            trace = self._create_trace(
                reasoning_steps=agent_trace_data.get("reasoning_steps", [
                    "Synthesized full pipeline context",
                    "Generated dual-report output (Business & Trace)",
                    "Validated cross-agent consistency"
                ]),
                options_considered=agent_trace_data.get("options_considered", ["Considered multiple report formats"]),
                decision_made=agent_trace_data.get("decision_made", "Generated final reports"),
                duration_ms=duration
            )
            
            # Include trace in JSON output
            report["agent_trace"] = trace
            
            return report, trace

        except Exception as e:
            duration = int((time.time() - start) * 1000)
            fallback = {
                "business_report": f"# Error during report generation\n\n{str(e)}",
                "trace_document": f"# Error during trace generation\n\n{str(e)}"
            }
            trace = self._create_trace(
                reasoning_steps=[f"Error: {str(e)}"],
                options_considered=["Attempted report generation"],
                decision_made="Failing visualization due to exception",
                duration_ms=duration,
                status="error"
            )
            return fallback, trace
